services:
  bboplace:
    container_name: agentbbo_bboplace
    image: gaozhixuan/bboplace-bench
    ports:
      - "8070:8080"

  dbtune-mariadb:
    container_name: agentbbo_http_mariadb_eval
    image: ${AGENTBBO_DBTUNE_MARIADB_IMAGE:-fakerstrawberry/agentbbo-dbtune-mariadb-eval:v1}
    ports:
      - "8080:8080"

  dbtune-surrogate:
    container_name: agentbbo_surrogate_http
    image: ${AGENTBBO_DBTUNE_SURROGATE_IMAGE:-fakerstrawberry/agentbbo-dbtune-surrogate-http-py37:v1}
    ports:
      - "8090:8090"
